[package]
name = "bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
winrt = { path = "../../winrt-rs" }

[build-dependencies]
winrt = { path = "../../winrt-rs" }

[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.19041.1"
